# Generated by Django 2.2 on 2020-03-19 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'branch',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'status',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='CustomerVisitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_address', models.TextField(blank=True, max_length=2000, null=True)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('assigned_cse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cse_visit.Branch')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cse_visit.Status')),
            ],
            options={
                'verbose_name_plural': 'customer_detail',
                'db_table': 'customer_detail',
            },
        ),
        migrations.CreateModel(
            name='CustomerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cse_visit.Branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cse_visit.CustomerVisitDetails')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'customer_assignment',
                'db_table': 'customer_assignment',
            },
        ),
    ]
