# Generated by Django 2.2 on 2020-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervisitdetails',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
