# Generated by Django 2.2 on 2020-03-23 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cse_visit', '0004_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervisitdetails',
            name='assigned_cse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customervisitdetails',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cse_visit.Branch'),
        ),
        migrations.AlterField(
            model_name='customervisitdetails',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cse_visit.Status'),
        ),
    ]
