# Generated by Django 2.2 on 2020-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse_visit', '0005_auto_20200323_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
